Cargo.toml
src/index.rs

refs https://github.com/paritytech/substrate/issues/7956
[Memmap is unmaintained](https://rustsec.org/advisories/RUSTSEC-2020-0077.html), fortunately a drop-in fork exists (memmap2). This PR switches the codebase to that crate and updates all dependencies to their latest version.
_Note_: as memmap is exposed in an external type, this change is a breaking major. Therefore, according to SemVer, the next version of this crate released should be `0.2.0` (at least).
_Note 2_: one main update that happened since the fork is [removing the winapi-dependency in favor of a localised equivialent](https://github.com/danburkert/memmap-rs/commit/37d18bbf421c4833c0f662f56889f83f7e72ad25).

Update Dependencies, switch memmap to memmap2 

---

src/column.rs
src/db.rs

This PR is implementing a simple fix for reindexing when the db is shut while reindexing (can see the effect by runing interupt.sh at https://github.com/cheme/parity-db/commit/ae6a19821b14a0921f67a8d4757912fe9712cfbb : basically the search existing index is broken and we amplify the index size by inserting multiple time the same index).
So this PR:
- adds reindexing by default at start.
- rebuild full key to reindex, this got an additional cost.
I guess a better fix would be to restore index from log, potentially allowing to avoid lookup of existing entry and avoid reindex all on restart, but having a check of full key without other assertion seems ok to me.

Reindexing at restart

---

check_be.sh
src/index.rs
src/stats.rs
src/table.rs

Quick fix for index transmute in be arch, and few utility function for index.
Removing the test and the .sh before merge could be a good idea (not that useful, except for implementing).

BE reindex

---

Cargo.toml
src/column.rs
src/compress.rs

Having everything pure rust just makes life simpler.
I ran the benchmark overriding it to do snappy compression by default and noted there were no ill effects, but I did note that the benchmark does not ever decompress anything at the moment so I've included a specific compression test.

Burnt sushi says snap is as snappy as snappy.

---

Cargo.toml
bench/core/src/lib.rs
src/column.rs
src/db.rs
src/index.rs
src/log.rs
src/options.rs
src/table.rs

Currently when we finish enacting WAL, we fsync/msync all data and delete the log file. Syncing data is expensive and may become a bottleneck under a heave write workload. We also can't keep writing to a next log while syncing data for previous log is in progress as the changes are kept in memory and this may lead to memory starvation.
This PR introduces WAL cleanup queue. Once log  file is fully read it is added to the cleanup queue. An additional thread syncs data and removes checkpointed logs from the queue. The tradeoff here is that if the sync is slow, log files may start accumulating wasting disk space. I consider this acceptable because eventually they will be deleted after the sync is complete.
Another change is that log records for index pages now only contain changes entries, …

Log cleanup queue

---

src/column.rs
src/db.rs
src/options.rs
src/table.rs

This PR remove Rc from value when not needed.
When rc is not use, but compression is possible (active in option and on a table above compression threshold), then a bit is added to indicate if compression is used.
Also rc uses full 32 byte when no compression is possible.

Remove REF from value table when unneeded.

---

.gitignore
Cargo.toml
src/db.rs
src/options.rs

Currently `Db::open` creates new database, even tho it shouldn't. This PR fixes this behaviour and adds 2 simple tests

prevent Db::open from creating new database

---

src/index.rs

should return () instead of Result<()>

fix: madvise_random on not(unix)

---

Cargo.toml
admin/src/lib.rs
src/column.rs
src/index.rs
src/migration.rs
src/options.rs
src/table.rs

Since size is stored as 16-bit little endian in value tables, it could potentially result in a byte value that matches  `MULTIHEAD` and `MULTIPART`.  
* Changes  byte order in `MULTIHEAD` and `MULTIPART` values to avoid collisions.
* Disables multipart tracking for fixed size entry tables.
* Removed v3 compatibility

Fix potential corruption

---

src/btree/iter.rs
src/btree/node.rs
src/db.rs

Iteration restart on commit was failing (I did not run the test enough, also found that tests sometime deadlock when using https://github.com/paritytech/parity-db/pull/47, but unrelated).
The commit overlay was a bit to much uncoupled from the backend resulting on inconsistencies.
This PR fix that. It also move the logic to restart iteration out of btree state iterator.

Fix iteration restart on commit.

---

.editorconfig
admin/src/bench/db.rs
admin/src/bench/mod.rs
admin/src/bench/sizes.rs
admin/src/lib.rs
admin/src/main.rs
rustfmt.toml
src/btree/btree.rs
src/btree/iter.rs
src/btree/mod.rs
src/btree/node.rs
src/column.rs
src/compress.rs
src/db.rs
src/display.rs
src/error.rs
src/file.rs
src/index.rs
src/lib.rs
src/log.rs
src/migration.rs
src/options.rs
src/stats.rs
src/table.rs

No offense, I know changing codestyle related things may offend devs. Just pick what seems to make sense to you.
Removing superfluous clones and references do make more sense.
But there are other things that seem to be serious, e.g. the unbound locks like this:
`let _ = Self::trigger_reindex(tables, reindex, self.path.as_path());`

Fix a truckload of clippy annotations, warnings and errors.

---

src/db.rs

While rebasing some branch, I realized that enact for `EnableCommitPipelineStages::DbFile` requires to flush before.

In tests enact requires flushing.

---

src/options.rs
src/table.rs

Closes #54.
The upgrade of version is not strictly necessary since we keep writing the compressed bit in the last size, but I forced the need by not reading it (looks cleaner).

Compressed in multipart head

---

Cargo.toml
src/options.rs

The way we use db_version, we should not change it when trying to upgrade metadata.
This PR adds an utility function and increase minor versioning.
Next I plan to change https://github.com/paritytech/substrate/blob/1bd5d786fda99d5a0c27c339226789ac047ea4ae/client/db/src/utils.rs#L279 to restore version and add some logging when this happen. (following code can also be simply removed but I find convenient that we can support harmless metadata change transparently, might be a bit of a footgun, but short term it is the fastest way to have a non breaking build).

Allow writing db version when writing metadata.

---

src/db.rs
src/options.rs

This fix is necessary to clearly understand when the database cannot be opened due to its non-existence (without string matching the error message).

Return a clear Error::DatabaseNotFound when database does not exist

---

admin/src/bench/mod.rs
admin/src/lib.rs
src/db.rs

If there are multiple threads waiting for the commit queue only one of them would be waken up when the queue is processed.

Fix a potential deadlock with parallel commits.

---

Cargo.toml
src/btree/mod.rs
src/btree/node.rs

Found orphan nodes are created in current btree implementation.
I also added an early exit, but I can remove the commit (does not really change perfs).

Remove orphan btree node.

---

src/stats.rs

As documented in https://doc.rust-lang.org/std/mem/union.MaybeUninit.html, 
```rust
let x: i32 = unsafe { MaybeUninit::uninit().assume_init() }; // undefined behavior! ⚠️
```

stats: fix UB in from_slice

---

src/migration.rs

Currently it works only with default column configuration, otherwise https://github.com/paritytech/polkadot/pull/5797 fails like this
```
Error:
0: Error removing column IncompatibleColumnConfig { id: 1, reason: "Column config mismatch. Expected \"preimage: false, uniform: false, refc: false, compression: 0, ordered: false\", got \"preimage: false, uniform: false, refc: false, compression: 0, ordered: true\"" }
```
I've fixed this by using the column configuration from the metadata for the DB validation.

Fix clear column

---

admin/src/bench/mod.rs
admin/src/bench/sizes.rs
admin/src/lib.rs
src/btree/iter.rs
src/btree/mod.rs
src/btree/node.rs
src/db.rs
src/index.rs
src/table.rs

This pr adds possibility to go back with btree iterator.
Reviewing by commits would make more sense, as the first two ones are minor refactoring. The rest of commits propagate reverse iterator from bottom to the top.
There are some minor problems with this code though. It repeats itself a lot, because I started of with just negating invariants of `next` function. Also, there is clearly not enough of tests for that, will add them soon.

Add reverse iteration for btree db

---

src/btree/btree.rs
src/btree/mod.rs
src/btree/node.rs
src/column.rs
src/db.rs
src/lib.rs
src/migration.rs
src/options.rs
src/stats.rs

I did get some code from old branch to propose this PR.
It expose a new operand to commit: `IncRc` that allow increase rc count in columns using rc, but without knowing the value.
This is not very important feature (can be use at one place in chain storage of substrate).
The PR also define a named enum `Change` that could be extended with different operand (I did have this in multiple branch so it make sense for me to have it).

Increment Rc and Change enum

---

src/db.rs
src/hash.rs
src/index.rs
src/lib.rs

Simplifies the lib.rs file
Inlines the const_assert macro that is only used once

Moves IdentityHash out of lib.rs

---

.github/workflows/rust.yml

Instrumentation provided by LLVM to track bad memory access
Useful when unsafe code is used
Allows to also run tests on nightly
Documentation: https://doc.rust-lang.org/beta/unstable-book/compiler-flags/sanitizer.html#addresssanitizer

Runs address sanitizer as part of the CI

---

src/btree/mod.rs
src/btree/node.rs

Removed assertion was incorrect, we skip Set operation on same key so we should not have two consecutive key in this case.
On the other hand whith reference operation on does not overwrite the other, so it make sense to have two consecutive identic keys (can also be key from a set operation).
I also did skip some Set operation when reference is in between to set operation but that's a corner case.
Makes me think reference operation could be optimized to only increase reference once (can be a bit tricky as if at any point the Rc is bellow 0, then folowing calls need to be skipped unless value written again, core pb is that we don't know the rc value when we want to skip such operation and probably don't want to fetch the rc, so should be optimizable but at a different location).
This issue …

Remove incorrect assertion

---

fuzz/.gitignore
fuzz/Cargo.toml
fuzz/README.md
fuzz/fuzz_targets/refcounted_model.rs
fuzz/fuzz_targets/simple_model.rs

Checks that the database behaves like an in-memory collection when a sequence of transactions and restarts are applied.
Covered cases:
- hash map and btree (for btree iteration order is checked)
- the 3 compressions
- reference counting or not

Adds basic model-based fuzzers

---

src/db.rs

CommitChangeSet is already private so this method is already unusable outside parity-db

Makes Db::commit_raw private

---

src/btree/mod.rs
src/btree/node.rs
src/column.rs
src/db.rs

Fix #104 
BTree columns were never used before with ref counted. My first idea was to forbid it, but it was fairly implementable I think.
A new parameter was added to write_existing_value to be able to use rc logic only on value (and not on indexing nodes).
While debugging I also found that root was uslessly written twice, so I did remove a write_plan function (second time was noop since changes where already writte).
Also had to disable node removal when the rc change did not delete value.
Also removed the node parent of the value marked as modified if the value index did not change.

allow using ref count for btree column

---

Cargo.toml
src/column.rs
src/table.rs

Currently Parity-DB is the only crate used by Substrate that is using `blake2-rfc`.
Everything else has been recently ported to RustCrypto `blake2`.
---
Please refer to this Substrate PR for some more details: https://github.com/paritytech/substrate/pull/12266

Replace blake2-rfc with blake2

---

Cargo.toml
fuzz/Cargo.toml
fuzz/src/lib.rs
src/column.rs
src/db.rs
src/error.rs
src/file.rs
src/index.rs
src/lib.rs
src/log.rs
src/migration.rs
src/options.rs
src/stats.rs
src/table.rs

Introduces the "instrumentation" feature.
When enabled the "set_number_of_allowed_io_operations" is exposed and allows to set the number of allowed I/O operations.
After this threshold is reached all I/O operations returns an error.
This required to wrap all I/O calls with the new "try_io!" macro that is an alias for "try!" if the "instrumentation" feature is not enabled.

Allows to simulate I/O errors

---

fuzz/fuzz_targets/refcounted_model.rs
fuzz/fuzz_targets/simple_model.rs
fuzz/src/lib.rs

Also do not instrument DB construction, in order to avoid quick failure due to #114

Fuzzer: Properly support instrumented errors during "drop"

---

src/file.rs

We already checked that the file already exists

TableFile::open: Remove unused create option

---

fuzz/fuzz_targets/refcounted_model.rs

If a value as usage count 0 then it might be GC so if a new reference is added to it should not make it alive again

Fuzzer: Ref-counted: makes sure to don't wrongly resurrect values

---

src/btree/iter.rs
src/btree/mod.rs
src/btree/node.rs
src/db.rs

After working on #124.
I did realize many variants of LastIndex were useless.
This PR changes:
LastIndex::Start -> LastIndex::Before(0) 
LastIndex::End -> LastIndex::Before(last separator + 1) . (so can be equal to ORDER).
LastIndex::After(i) -> LastIndex::Before(i + 1)
Also a seek operation do not need a direction.
And seek_to_last is now using a variant of SeekTo enum.
Close #124

Refactor btree iterator last index

---

src/btree/iter.rs
src/btree/node.rs
src/compress.rs
src/db.rs
src/file.rs
src/log.rs
src/table.rs

- Clippy suggestions
- Comments position in the file (avoids `use` calls both before and after the main comment of the file)
- Typos

Minor code cleanups

---

CHANGELOG.md
Cargo.toml

I added a CHANGE_LOG too, I just did put the two item that breaks api that I remember of.
Plan to release 0.4.0 as CI test failure from substate looks correlated to behavior on change of record_id.
(does not fix the corruption observed by user though)

Changing version to v0.4.0 for release.

---

src/db.rs

Not actually required anywhere

Removes skip_check_lock option

---

src/db.rs

There was nothing that checked that `col` is a valid column id.
Closes #137

Fixes a possible crash during log validation

---

src/error.rs

It simulates better a disk or network error that the previous behavior of only failing once.

I/O simulation: always fail after the first failure

---

fuzz/Cargo.toml
fuzz/fuzz_targets/refcounted_model.rs
fuzz/fuzz_targets/simple_model.rs
fuzz/src/lib.rs
src/db.rs
src/options.rs

Makes fuzzing way more deterministic
Allows a more careful model of which state are already  persisted and which state is not
Does also some refactoring of `Db` test related API to be able to call them from the fuzzer

Makes fuzzer call explicitly I/O operations

---

admin/src/bench/mod.rs
src/column.rs
src/index.rs

Suggested by a new nightly Clippy lint

Removes some trivial casts

---

fuzz/fuzz_targets/refcounted_model.rs
fuzz/fuzz_targets/simple_model.rs
fuzz/src/lib.rs

* Makes fuzzer support the recovery case "the disk becames unreadable during recovery so the fuzzer model believes the database is empty. After the subsequence DB restart the recovery process works and past commits get properly reneacted, leading to a DB state different from the fuzzer model".
* Removes a lot of code duplication in the fuzzers

Makes fuzzer support more recovery edge cases

---

fuzz/src/lib.rs
src/db.rs
src/log.rs
src/table.rs

Allows to avoid having a global state on Log (Reading vs Idle) and to be able to flush log even if the next file is not fully enacted

Log: Adds a read queue

---

src/btree/iter.rs

Not a breaking change, cannot be used outside the crate

Removes "pub" modifier on methods with private input types

---

src/table.rs

Removes TableKey::index (private dead code)

---

src/log.rs

If Log.cleanup_queue is partially drained between the computation of the number of logs to clean (the "count" parameter) and the actual call to "drain", the drain method was panicking.
The changed code only drains at most the number of elements of the queue, avoiding the panic risk.
Found using Loom

Avoid a race-condition leading to crash in Log::clean_logs

---

src/table.rs

It does not make sense at all on containers like Vec<u8>

Implements Entry::new_uninit only where it's fairly safe

---

src/stats.rs

Reduces the size of the ColumnStats type (14440 bytes before 176 bytes after) in order to avoid possible stack overflow

ColumnStats: uses Vec for histograms

---

Cargo.toml
src/column.rs
src/db.rs
src/error.rs
src/index.rs
src/lib.rs
src/table.rs

An interrupted reindexing process would result in duplicated index entries on the next attempt. The check for existing entries when reindexing is incorrect, as it checks for full key when only partial key is available.

Fix index corruption on reindex

---

src/index.rs

Allows to avoid a bound check on each `read_entry` call

IndexTable::find_entry: add assertion bound checking

---

Cargo.toml
fuzz/src/lib.rs
src/btree/btree.rs
src/btree/iter.rs
src/btree/mod.rs
src/btree/node.rs
src/column.rs
src/db.rs
src/error.rs
src/log.rs
src/migration.rs

I notice that the `copy_to_overlay` method clones the `value` vector in Hash index mode and clones both the `key` and `value` vectors in Btree index mode, which seems to be an unnecessary overhead, this PR tries to, instead, clone the pointer type `Arc<Vec<u8>>` which is much cheaper, please let me know your feedback, thanks!

Reduce alloc in copy_to_overlay

---

Cargo.toml
src/index.rs
src/lib.rs

```
$ cargo +nightly bench --features bench bench
Finished bench [optimized + debuginfo] target(s) in 0.06s
Running unittests src/lib.rs (target/release/deps/parity_db-21d11d42e7884130)
running 2 tests
test index::test::bench_find_entry     ... bench:          29 ns/iter (+/- 0)
test index::test::bench_find_entry_sse ... bench:          13 ns/iter (+/- 0)
```
Also added a small optimization for `chunk_at`

Benchmarks for find_entry

---

admin/Cargo.toml
admin/src/bench/mod.rs
admin/src/lib.rs

Applies the hash function when generating keys and uses a uniform column. It also generates the keys before running the rest of the stress test so the hash function isn't used during the test. I found this useful for profiling.
**Caveats**
Uses memory to store all the keys.
When appending to a database it only generates keys for the current run. Reader threads can read from the whole database so will sometimes end up executing the hash function during the test.

Uniform keys option for stress test.

---

.github/workflows/rust.yml
Cargo.toml
src/column.rs
src/db.rs
src/index.rs

This fixes a potential DB corruption on write error. When the database is closed with an error, all existing logs must be preserved so that log recovery may fix it on next open.

Preserve logs on write error. 

---

src/index.rs

In case there are multiple matches for the first group of 4 etries, the `sub_index` check logic would only consider the first match.

Fix find_entry_sse

---

src/btree/btree.rs
src/btree/mod.rs
src/btree/node.rs
src/table.rs

Intend to remove panic behavior on btree content reading.
fix https://github.com/paritytech/parity-db/issues/191

Check read bound for btree nodes.

---

admin/src/bench/mod.rs

Added options for controlling writer thread sleeps so that they can pause after a number of commits.
Made reader threads default to not reading pruned values. Old behaviour can be enabled with an option.
These should give a slightly more representative way of measuring query performance.

Representative query timing

---

admin/src/lib.rs
src/column.rs
src/db.rs
src/index.rs
src/migration.rs
src/table.rs

* Added an alternative hash column iteration. The index is copied to memory, sorted by disk offset and then iterated. This makes checking large databases 100x faster.
* Also added some code to follow free entry lists and check them for correctness.

Improve DB validation tool

---

.github/workflows/rust.yml
src/db.rs

On machines with slow fsync it is possible that the log cleanup queue grows to gigabytes while fsync is in progress. This PR add a limit to the cleanup queue, pausing commits if it grows too much,
Also tweaked error handling for the log recovory. If recovery fails for reasons other than the bad log file we keep the log files around, instead of deleting them and hoping fo the best. If replay is successfull, the logs are deleted right away (after fsync), instead of waiting for the database to be closed.

Limit log cleanup queue

---

Cargo.toml
src/index.rs

In rare cases when target partial key is all zeroes and the index chunk contains precceding empty entries, these empty entries are returned instead.

Fix find_entry for zero partial key

---

Cargo.toml
src/index.rs

Currently `madvise` call for the random IO hint is only performed on the new index creation. It should be done on opening an existing index as well.

Call madvise for existing index files

---

src/db.rs

While debugging another branch, this counter looks odd to me.
I feel like it should be like in this commit.
But maybe this was a trick to avoid some concurrency issue (iiuc this makes cleaning the log overlay always late by one record id).
cc @arkpar @MattHalpinParity

Record id for cleaning log overlay.

---

Cargo.toml
admin/src/lib.rs
src/column.rs
src/file.rs
src/index.rs
src/log.rs
src/table.rs

This works much faster when performance is limited by OS page cache. When the database is relatively small and fits entirely in the page cache, making kernel calls becomes too expensive.
Also removed extra copy to a temp buffer when reading values from file. 
Also optimized overlay layout a bit. The top level is a vec now instead of a hashmap.

Use mmap IO for value tables

---

src/file.rs

Make `madvise_random` compatible with non-Unix OS

---

.github/workflows/rust.yml
src/file.rs

Disable mmap address space reservation on windows as it is not supported by memmap2-rs

CI for windows and macos

---

Cargo.toml
admin/Cargo.toml
src/db.rs
src/file.rs
src/index.rs
src/lib.rs
src/log.rs

Force alignment for all chunk buffers

---

src/lib.rs

Add support for [LoongArch64](https://doc.rust-lang.org/rustc/platform-support/loongarch-linux.html) (A tier-2 with host tools target).

Add support for LoongArch64

---

fuzz/src/lib.rs
src/db.rs
src/table.rs

Fix value table iteration vs log processing race

---

Cargo.toml
src/file.rs

Windows requires custom options to be specified instead of doing this on a file handle

Disable read-ahead on Windows
