src/table.rs

This PR uses read and write with offset api on table.
Not sure it is very interesting, it was part of a different branch with different table layout, and I was wondering about removing Rc when not needed, and it may be easier with this code as a start.

Table relative indexes read and write.

---

src/file.rs
src/lib.rs
src/table.rs

This PR extract file related methods from table module.
It also change the initial file capacity to align file size.

Extract file utility from table module.

---

Cargo.toml
src/file.rs

This PR fix a regression from #46.
Also increase crate versioning.

Fix capacity initializing.

---

admin/src/lib.rs
src/column.rs
src/db.rs
src/index.rs
src/options.rs
src/table.rs

Fixes possible  corruption on critical write error.
Also include a small refactoring.

Stability fix and small refactoring

---

admin/src/bench/mod.rs

Seed for stress test did not work properly.
This fixes it, keeping seed working as an offset (it is convenient sometime).

fix stress test seed

---

Cargo.toml
src/db.rs

Also added fdlimit raise on test_random, and added `process_reindex` on shutdown.

Change tests to use no threads.

---

src/db.rs

When the parent directory for the database does not exist, 
the open (no-create) fails upon lock-attempt with an `std::io::Error`
before the control reaches `load_and_validate_metadata`.

Proper handling for Error::DatabaseNotFound (std::fs::create_dir_all scenario)

---

src/db.rs

* unnecessarily public function;
* unneeded explicit scope: probably an echo of some previous refactoring.

Does not fix anything: just removes two benign things that raise unnecessary questions.

---

admin/src/bench/mod.rs
src/column.rs
src/db.rs

Also made commit counting in the bench tool more precise.

Fix potential deadlock on double reindex

---

src/file.rs

Code is analogous to Rust standard library.
Fixes #76

Ensure all bytes are read/written on Windows

---

src/column.rs
src/file.rs

Formatting fixes after #77.
This is due to nightly formatting options used.

Fix formatting

---

admin/src/lib.rs
src/column.rs
src/db.rs
src/lib.rs
src/stats.rs

Expose basic stats

---

admin/Cargo.toml
admin/src/main.rs

The targets in the code vs the Cargo.toml were different

Upgrades jemallocator and uses it anywhere but msvc

---

src/db.rs

Makes sure that panics in worker threads are logged

Logs errors when joining threads on drop

---

src/btree/iter.rs
src/btree/mod.rs
src/btree/node.rs
src/db.rs

This is a small refactor of iterator logic when switching backward/forward.
Mainly removea bit of redundant code and makes that we do not return same value when changing iteration direction.
Currently draft as I need to reread it and clippy it, but @Tpt it may be interesting to run your fuzzer on this branch.

Last state iterator

---

.github/workflows/rust.yml
fuzz/fuzz_targets/refcounted_model.rs
fuzz/fuzz_targets/simple_model.rs
fuzz/src/lib.rs

Requires #109 to be fully functional but the code is independant from it.

Improves fuzzers

---

src/options.rs

There is still two I/O operations (create + write_all) and write_all might also do multiple operations...
Closes #115

Makes metadata write more atomic-like

---

src/log.rs

Note: no need for calling "clear_replay_log", the corrupt file will be dropped anyway
Closes #117

Recovery: do not badly fail on corrupted log

---

src/file.rs
src/table.rs

Makes ValueTable::init_with_entry cleanly abort on error

---

admin/src/lib.rs
src/column.rs
src/db.rs
src/index.rs

Allows to fuzz random disk crash

Inserts instrumented errors on mmap access

---

src/migration.rs
src/table.rs

Not sure if it is welcome because it makes debugging a bit more cumbersome.

Uses tempdir in all tests

---

src/db.rs
src/options.rs

Fixes https://github.com/paritytech/parity-db/issues/142
https://github.com/paritytech/polkadot/pull/6106

Support for adding new columns in existing db

---

.github/workflows/rust.yml
src/db.rs
src/log.rs

Clean logs using the usual process even in case of replay or db failure

---

src/btree/iter.rs
src/db.rs

Properly reset BTree iteration state on boundaries

---

src/compress.rs

Added `FromStr` for `CompressionType`
This is useful for clients with compression type adjustable via, e.g., a config file or CLI flag.

implement FromStr for CompressionType

---

.github/workflows/rust.yml

Uses also the same building blocks as the other actions

Renames "build" CI job to "test"

---

src/index.rs

Change target logic for no sse2.

No sse2 target

---

src/index.rs
src/lib.rs

Makes clear which platforms are supported

Fail compilation if not on amd64 or arm64

---

fuzz/fuzz_targets/refcounted_model.rs
fuzz/fuzz_targets/simple_model.rs
fuzz/src/lib.rs

Allows to more carefully look for data loss

Fuzzer: model more carefully what is written to disk

---

.github/workflows/rust.yml
src/file.rs
src/log.rs

Another take on the problem described in #201

Ensure log deletion order

---

CHANGELOG.md
Cargo.toml
src/log.rs

Bump version to include multi tree changes
